// static CDN
// static CDN
export const CDN_PREFIX = 'https://cdn.jsdelivr.net/npm'

const readRuntimeVar = name => globalThis?.[name]

// server side salt
export const SALT = readRuntimeVar('SCN_SALT')
// server side secret
export const SECRET = readRuntimeVar('SCN_SECRET')
export const getSalt = () => readRuntimeVar('SCN_SALT')
export const getSecret = () => readRuntimeVar('SCN_SECRET')

// admin
export const getAdminPath = () => readRuntimeVar('SCN_ADMIN_PATH') || '/admin'
export const getAdminPassword = () => readRuntimeVar('SCN_ADMIN_PW')
// Kept for compatibility with callers that import the old constants. Request
// handlers should use the getters because Cloudflare bindings are available
// after the Worker module has been evaluated.
export const ADMIN_PATH = getAdminPath()
export const ADMIN_PW = getAdminPassword()
export const getSlugLength = () => parseInt(readRuntimeVar('SCN_SLUG_LENGTH') || '3', 10)
// Access R2 config at runtime instead of module load time
export const getEnableR2 = () => readRuntimeVar('SCN_ENABLE_R2') === '1'
export const getR2Domain = () => (typeof readRuntimeVar('SCN_R2_DOMAIN') !== 'undefined' ? readRuntimeVar('SCN_R2_DOMAIN') : '')
export const getGaMeasurementId = () => (typeof readRuntimeVar('SCN_GA_MEASUREMENT_ID') !== 'undefined' ? String(readRuntimeVar('SCN_GA_MEASUREMENT_ID') || '').trim() : '')
const WEBTALK_DEFAULTS = {
    scriptUrl: 'https://webtalk-nine.vercel.app/webtalk.js',
    scope: 'meta',
    siteId: 'david888-wiki',
    aiEndpoint: 'https://webtalk-nine.vercel.app/api/webtalk/ai',
}
const getHttpUrl = value => {
    try {
        const url = new URL(String(value || '').trim())
        return url.protocol === 'https:' || url.protocol === 'http:' ? url.href : ''
    } catch {
        return ''
    }
}
export const getWebtalkConfig = () => {
    if (readRuntimeVar('SCN_ENABLE_WEBTALK') !== '1') return { enabled: false }

    const scriptUrl = getHttpUrl(readRuntimeVar('SCN_WEBTALK_SCRIPT_URL') ?? WEBTALK_DEFAULTS.scriptUrl)
    const aiEndpoint = getHttpUrl(readRuntimeVar('SCN_WEBTALK_AI_ENDPOINT') ?? WEBTALK_DEFAULTS.aiEndpoint)
    if (!scriptUrl || !aiEndpoint) return { enabled: false }

    return {
        enabled: true,
        scriptUrl,
        scope: String(readRuntimeVar('SCN_WEBTALK_SCOPE') ?? WEBTALK_DEFAULTS.scope).trim(),
        siteId: String(readRuntimeVar('SCN_WEBTALK_SITE_ID') ?? WEBTALK_DEFAULTS.siteId).trim(),
        aiEndpoint,
    }
}
export const APP_NAME = (typeof readRuntimeVar('SCN_APP_NAME') !== 'undefined') ? readRuntimeVar('SCN_APP_NAME') : 'david888 wiki'

// Persisted preview/share widths. Keep the API default aligned with the
// editor's initial desktop preview so a newly published API note renders the
// same way in edit and share views.
export const PREVIEW_WIDTH_VALUES = Object.freeze(['100%', '960px', '1200px', '1440px'])
export const DEFAULT_PREVIEW_WIDTH = '1200px'
export const normalizePreviewWidth = (value, fallback = DEFAULT_PREVIEW_WIDTH) => {
    const safeFallback = PREVIEW_WIDTH_VALUES.includes(fallback) ? fallback : DEFAULT_PREVIEW_WIDTH
    if (value === undefined || value === null || value === '') return safeFallback

    const normalized = String(value).trim()
    return PREVIEW_WIDTH_VALUES.includes(normalized) ? normalized : null
}

// Vault modes and expiration options
export const VAULT_MODES = Object.freeze(['standard', 'burn_after_reading', 'timelock', 'deadman'])

export const VAULT_MODE_INFO = Object.freeze({
    standard: {
        'zh-TW': '標準發布',
        'en-US': 'Standard Public',
    },
    burn_after_reading: {
        'zh-TW': '閱後即焚',
        'en-US': 'Burn After Read',
    },
    timelock: {
        'zh-TW': '定時解鎖 (時間膠囊)',
        'en-US': 'Time-Locked Capsule',
    },
    deadman: {
        'zh-TW': '亡者開關 (保活心跳)',
        'en-US': "Dead Man's Switch",
    },
})

export const EXPIRATION_OPTIONS = Object.freeze([
    { value: 'never', labelZh: '永久有效（預設）', labelEn: 'Never (Default)' },
    { value: '10m', labelZh: '10 分鐘', labelEn: '10 minutes' },
    { value: '1h', labelZh: '1 小時', labelEn: '1 hour' },
    { value: '1d', labelZh: '1 天 (24小時)', labelEn: '1 day (24 hours)' },
    { value: '7d', labelZh: '7 天 (1週)', labelEn: '7 days (1 week)' },
    { value: '30d', labelZh: '30 天 (1個月)', labelEn: '30 days (1 month)' },
])

export const TIMELOCK_OPTIONS = Object.freeze([
    { value: '1h', labelZh: '1 小時後', labelEn: '1 hour later' },
    { value: '1d', labelZh: '1 天後', labelEn: '1 day later' },
    { value: '3d', labelZh: '3 天後', labelEn: '3 days later' },
    { value: '7d', labelZh: '7 天後 (1週)', labelEn: '7 days later' },
    { value: '30d', labelZh: '30 天後 (1個月)', labelEn: '30 days later' },
])

export const PULSE_INTERVAL_OPTIONS = Object.freeze([
    { value: '3d', labelZh: '3 天', labelEn: '3 days' },
    { value: '7d', labelZh: '7 天 (1週)', labelEn: '7 days (1 week)' },
    { value: '14d', labelZh: '14 天 (2週)', labelEn: '14 days (2 weeks)' },
    { value: '30d', labelZh: '30 天 (1個月)', labelEn: '30 days (1 month)' },
])

export const VAULT_QUICK_PRESETS = Object.freeze([
    {
        id: 'otp',
        icon: '🛡️',
        iconName: 'shieldAlert',
        labelZh: '一次性密碼',
        labelEn: 'One-Time Password',
        mode: 'burn',
        expiresIn: '1h',
        descZh: '閱後即焚，最多有效 1 小時',
        descEn: 'Burn after reading, max 1h',
        template: '# 一次性密碼 / One-Time Password\n\n- 帳號 / Username: \n- 暫時密碼 / Password: \n- 安全注意: 此分享僅限閱覽 1 次，閱畢即刻從伺服器永久銷毀。\n',
    },
    {
        id: 'crypto',
        icon: '₿',
        iconName: 'bitcoin',
        labelZh: '加密資產傳承',
        labelEn: 'Crypto Inheritance',
        mode: 'deadman',
        pulseInterval: '30d',
        descZh: '亡者開關，30 天無保活自動解鎖',
        descEn: "Dead man's switch, 30d pulse",
        template: '# 加密資產遺產傳承指引 / Crypto Inheritance\n\n## 1. 錢包與保管箱資訊\n- 硬體錢包型號 / 位置：\n- 助記詞保管位置：\n\n## 2. 繼承人存取指示\n請按照以下步驟前往授權機構或輸入密鑰進行資產繼承...\n',
    },
    {
        id: 'whistleblower',
        icon: '📢',
        iconName: 'megaphone',
        labelZh: '吹哨揭弊保護',
        labelEn: 'Whistleblower',
        mode: 'deadman',
        pulseInterval: '7d',
        descZh: '亡者開關，7 天無心跳即公開事證',
        descEn: "Dead man's switch, 7d release",
        template: '# 公共利益揭弊文件 / Whistleblower Disclosure\n\n## 核心揭露事證\n本備忘錄受亡者開關保護。若作者連續 7 天未簽到保活，本檔案將自動對外公開。\n\n## 佐證資料清單\n1. ...\n',
    },
    {
        id: 'launch',
        icon: '🚀',
        iconName: 'rocket',
        labelZh: '產品發布解鎖',
        labelEn: 'Product Launch',
        mode: 'timelock',
        unlockIn: '7d',
        descZh: '時間膠囊，7 天後準時解鎖公開',
        descEn: 'Time capsule, 7d launch unlock',
        template: '# 新產品發布公告 / Product Launch Announcement\n\n> 🔒 本文檔於倒數結束前處於時間封印狀態。\n\n## 發布內容與優惠活動\n- 正式版功能亮點：\n- 限時促銷代碼：\n',
    },
    {
        id: 'birthday',
        icon: '🎁',
        iconName: 'gift',
        labelZh: '生日驚喜禮物',
        labelEn: 'Birthday Gift',
        mode: 'timelock',
        unlockIn: '1d',
        descZh: '時間膠囊，1 天後 (生日當天) 揭曉',
        descEn: 'Time capsule, unlock on birthday',
        template: '# 生日快樂！ / Happy Birthday! 🎂\n\n親愛的朋友：\n\n祝你生日快樂！這是一份為你提前封印的驚喜禮物。\n\n- 禮物兌換代碼 / 祝福信件：\n',
    },
    {
        id: 'legal',
        icon: '⚖️',
        iconName: 'scale',
        labelZh: '司法保全留存',
        labelEn: 'Legal Hold',
        mode: 'standard',
        expiresIn: '30d',
        descZh: '標準分享，30 天後自動過期下架',
        descEn: 'Standard share, 30 days hold',
        template: '# 法律保全與存證紀錄 / Legal Hold Notice\n\n本通知所載內容依循保全程序存證，預計保留 30 天後自動過期下架。\n\n- 案件編號：\n- 保全事由：\n',
    },
    {
        id: 'scavenger',
        icon: '🎯',
        iconName: 'target',
        labelZh: '闖關尋寶線索',
        labelEn: 'Scavenger Hunt',
        mode: 'timelock',
        unlockIn: '1h',
        descZh: '時間膠囊，1 小時後解鎖下一關線索',
        descEn: 'Time capsule, 1h clue unlock',
        template: '# 闖關尋寶 — 第 1 道線索 / Scavenger Hunt Clue #1\n\n恭喜你來到這裡！解開以下謎題即可獲得下一關座標：\n\n> 謎題：\n',
    },
    {
        id: 'course',
        icon: '📅',
        iconName: 'graduationCap',
        labelZh: '課程定時教材',
        labelEn: 'Course Content',
        mode: 'timelock',
        unlockIn: '7d',
        descZh: '時間膠囊，下週上課前定時解鎖',
        descEn: 'Time capsule, 7d class release',
        template: '# 第 1 單元教材與隨堂解答 / Course Content & Solutions\n\n本教材於課堂開始時自動解鎖供修課同學研讀。\n\n## 重點複習\n1. ...\n',
    },
    {
        id: 'backup',
        icon: '🛟',
        iconName: 'lifeBuoy',
        labelZh: '緊急災備通道',
        labelEn: 'Emergency Backup',
        mode: 'deadman',
        pulseInterval: '14d',
        descZh: '亡者開關，14 天無簽到自動釋出應急',
        descEn: "Dead man's switch, 14d backup",
        template: '# 緊急災難復原通道 / Emergency Backup & Recovery\n\n## 救援存取金鑰\n- 備用 DNS 主控台：\n- 緊急 SSH 救援公鑰：\n- 第一線緊急應變小組聯絡電話：\n',
    },
    {
        id: 'secret',
        icon: '🔑',
        iconName: 'key',
        labelZh: '機密金鑰分享',
        labelEn: 'Shared Secret',
        mode: 'burn',
        expiresIn: '1d',
        descZh: '閱後即焚，適合安全傳送金鑰憑據',
        descEn: 'Burn after reading credentials',
        template: '# 機密憑據傳遞 / Confidential Shared Secret\n\n```env\nAPI_KEY=\nDATABASE_PASSWORD=\nCLIENT_SECRET=\n```\n\n⚠️ 本連結為一次性閱後即焚分享。\n',
    },
])

// supported language
export const SUPPORTED_LANG = {
    'en-US': {
        quickStartTemplates: 'Quick Start Templates',
        quickPresetApplied: 'Preset applied: ',
        setPW: 'Edit Lock',
        changePW: 'Edit Lock',
        setViewPW: 'View Lock',
        changeViewPW: 'View Lock',
        share: 'Share URL',
        preview: 'Preview',
        lastModified: 'Saved',
        copy: 'Copy',
        copied: 'Copied!',
        copyFailed: 'Copy failed',
        emptyPH: 'There are many like it, but this one is mine...',
        tipEncrypt: 'This Note has been encrypted, please enter password!',
        tip404: '404, Nothing here',
        published: 'Published',
        publicIndex: 'Public index',
        publicIndexEnable: 'Add to sitemap',
        publicIndexDisable: 'Remove from sitemap',
        publicIndexOn: 'Indexed',
        publicIndexOff: 'Private',
        publicIndexUpdatedOn: 'Added to public index.',
        publicIndexUpdatedOff: 'Removed from public index.',
        annotations: 'Paragraph annotations',
        annotationsEnable: 'Allow paragraph annotations',
        annotationsDisable: 'Disable paragraph annotations',
        annotationsOn: 'Open',
        annotationsOff: 'Off',
        annotationsUpdatedOn: 'Paragraph annotations are open.',
        annotationsUpdatedOff: 'Paragraph annotations are closed.',
        shareExpiration: 'Expiration',
        shareExpirationNever: 'Never (Default)',
        shareExpiration10m: '10 minutes',
        shareExpiration1h: '1 hour',
        shareExpiration1d: '1 day (24 hours)',
        shareExpiration7d: '7 days (1 week)',
        shareExpiration30d: '30 days (1 month)',
        burnAfterReading: 'Burn After Read',
        burnAfterReadingOn: 'Burn On',
        burnAfterReadingOff: 'Burn Off',
        burnAfterReadingHint: 'Self-destructs after first external read',
        burnRevealTitle: 'Confidential Share • Burn After Reading',
        burnRevealDesc: 'This confidential share is set to burn after reading. It can only be read once. Click the button below to reveal the content and permanently destroy this share link from the server.',
        burnRevealBtn: 'Reveal & Destroy',
        burnRevealWarning: 'Warning: Once destroyed, reloading or closing the window will permanently lose access.',
        shareBurnedTitle: 'Share Destroyed',
        shareBurnedDesc: 'This share was set to burn after reading and has already been viewed and permanently destroyed.',
        shareExpiredTitle: 'Share Expired',
        shareExpiredDesc: 'This share link has expired and is no longer accessible.',
        authorPreviewNotice: 'Author Preview Mode: Burn-after-reading and expiration timers are paused for you; only external visits trigger self-destruction.',
        burnActiveNotice: 'This share has been destroyed from the server. Reloading or navigating away will prevent further access.',
        shareVaultMode: 'Seal Access Control',
        shareModeStandard: 'Standard Public',
        shareModeBurn: 'Burn After Read',
        shareModeTimeLock: 'Time-Locked Capsule',
        shareModeDeadman: "Dead Man's Switch",
        shareUnlockIn: 'Unlock In',
        shareUnlockIn1h: '1 hour later',
        shareUnlockIn1d: '1 day later',
        shareUnlockIn3d: '3 days later',
        shareUnlockIn7d: '7 days later',
        shareUnlockIn30d: '30 days later',
        shareTimeLockedTitle: 'Time-Locked Capsule',
        shareTimeLockedDesc: 'This note is cryptographically sealed and will automatically unlock at the designated time.',
        shareDeadmanTitle: "Dead Man's Switch Active",
        shareDeadmanDesc: 'Author pulse is active and the vault remains confidential. If the author fails to check in, this vault auto-releases.',
        pulseInterval: 'Pulse Interval',
        pulseInterval3d: '3 days',
        pulseInterval7d: '7 days (1 week)',
        pulseInterval14d: '14 days (2 weeks)',
        pulseInterval30d: '30 days (1 month)',
        pulseNowBtn: 'Pulse Now (Check-in)',
        pulseSuccess: 'Pulse successful! Check-in interval refreshed.',
        pulseCopyLink: 'Copy Private Pulse Link',
        pulseCopied: 'Private pulse link copied to clipboard! Keep it safe.',
        authorTimeLockPreview: 'Author Preview: This time-capsule is locked for visitors and unlocks at {time}.',
        authorDeadmanPreview: "Author Preview: Dead Man's Switch active. Next pulse deadline: {time}.",
        shareLink: 'Share',
        shareLinkTitle: 'Open shared page in a new tab',
        recentSharesTitle: 'Recent shares',
        editLockTitle: 'Edit lock',
        readLockTitle: 'View lock',
        backToEdit: 'Back to edit',
        present: 'Present',
        presentTitle: 'Open full-screen presentation mode',
        presentationUnavailable: 'No content to present',
        presentationClose: 'Close presentation',
        presentationFailed: 'Presentation failed: ',
        width: 'Width',
        full: 'Full',
        previewDevice: 'Preview device',
        desktop: 'Desktop',
        mobile: 'Mobile',
        skill: 'Skill',
        skillTitle: 'Open AI skill markdown',
        apiDoc: 'API',
        apiDocTitle: 'Open API markdown documentation',
        startRecording: 'Live voice recording',
        importMarkdown: 'Import Office, PDF, Audio (Transcript) or Markdown',
        importFileMarkdown: 'Import file (creates a Markdown note)',
        importAudioMarkdown: 'Import audio (Transcript)',
        importAudioSmartFormatMarkdown: 'Import audio (Smart format)',
        importWebsiteMarkdown: 'Import website (creates a Markdown note)',
        importFileBlock: 'Import file (convert to blocks)',
        importAudioBlock: 'Import audio (Transcript to blocks)',
        importAudioSmartFormatBlock: 'Import audio (Smart format to blocks)',
        importWebsiteBlock: 'Import website (convert to blocks)',
        creatingMarkdownNote: 'Creating Markdown note...',
        importBlockMessage: 'Imported content will be converted into blocks. Some advanced Markdown may be simplified.',
        importActionInsertBlock: 'Insert after current block',
        exportMarkdown: 'Export markdown file',
        exportPdf: 'Print or export PDF',
        convertingDocument: 'Converting document to Markdown...',
        transcribingAudio: 'Transcribing audio to transcript...',
        transcribingAudioSmartFormat: 'Transcribing audio and smart-formatting the content...',
        markdownImported: 'Markdown imported.',
        documentImported: 'Document converted and imported successfully.',
        audioTranscribed: 'Audio transcript generated successfully.',
        audioSmartFormatted: 'Audio transcript was smart-formatted successfully.',
        markdownImportFailed: 'Document conversion or import failed',
        audioTranscribeFailed: 'Audio transcription failed',
        importOptionTitle: 'Import Options',
        importOptionMessage: 'How would you like to handle the imported content?',
        importActionReplace: 'Replace All',
        importActionInsert: 'Insert at Cursor',
        importActionCancel: 'Cancel',
        savedAtTitle: 'Saved at',
        language: 'Language',
        publishNudgeTitle: 'Save and publish this note?',
        publishNudgeText: 'This unpublished note is not saved yet. Publish now to save the current content and get a share URL.',
        publishApplyChoices: 'Apply choices',
        publishPreferencePublish: 'Publish',
        publishPreferencePublishHelp: 'Save the current note and create a public share URL.',
        publishPreferenceAutosave: 'Autosave',
        publishPreferenceAutosaveHelp: 'Save changes 10 seconds after you stop typing.',
        publishPreferencePublicIndex: 'Public index',
        publishPreferencePublicIndexHelp: 'Include the share URL in sitemap.xml so search engines may discover it.',
        publishPreferencesRemembered: 'These choices will be remembered on this device.',
        publicationDraft: 'Draft',
        publicationPublished: 'Published',
        publicationUrl: 'Share URL',
        publicationVersions: 'Retained versions',
        publicationViews: 'Unique views',
        publicationUpdated: 'Last saved',
        publicationPendingHint: 'Publish to show the share URL and reader statistics.',
        later: 'Later',
        unpublishConfirm: 'Unpublish this share link?',
        uploadFailed: 'Upload failed',
        uploadError: 'Upload error: ',
        uploading: 'Uploading...',
        err: 'Error',
        pepw: 'Please enter password.',
        passwordConfirm: 'Continue',
        passwordCancel: 'Cancel',
        pwcnbe: 'Password is empty!',
        enpw: 'Enter a new password (Keeping it empty will remove the current password)',
        pwss: 'Password set successfully.',
        pwrs: 'Password removed successfully.',
        shareAndHistory: 'Shares & history',
        history: 'History',
        historyTitle: 'Version history',
        historyPreview: 'Preview',
        historyRaw: 'Raw',
        historyRefresh: 'Refresh',
        historyRestore: 'Restore',
        historyCopyContent: 'Copy content',
        historyCurrentVersion: 'Current',
        historySelectedVersion: 'Selected',
        historyNoSelection: 'Select a version to compare.',
        historyLoading: 'Loading history...',
        historyEmpty: 'No saved history yet. Once older versions are retained, they will appear here.',
        historyDisabled: 'Note history is disabled for this deployment.',
        historyUnavailableOnShare: 'Version history is only available on the edit page.',
        historyRestoreConfirm: 'Restore this version and overwrite the current note?',
        historyRestoreDone: 'Version restored.',
        historyCopiedContent: 'Content copied.',
        historyChars: 'chars',
    },
    'zh-TW': {
        quickStartTemplates: '快速情境範本',
        quickPresetApplied: '已套用情境範本：',
        setPW: '編輯鎖',
        changePW: '編輯鎖',
        setViewPW: '閱讀鎖',
        changeViewPW: '閱讀鎖',
        share: '發布分享',
        preview: '預覽',
        lastModified: '保存',
        copy: '複製',
        copied: '已複製',
        copyFailed: '複製失敗',
        emptyPH: '',
        tipEncrypt: '這是一篇加密筆記，你必須先輸入密碼',
        tip404: '404，你要找的東西並不存在',
        published: '已發布',
        publicIndex: '公開索引',
        publicIndexEnable: '加入 sitemap',
        publicIndexDisable: '移出 sitemap',
        publicIndexOn: '已收錄',
        publicIndexOff: '未收錄',
        publicIndexUpdatedOn: '已加入公開索引。',
        publicIndexUpdatedOff: '已從公開索引移除。',
        annotations: '段落註解',
        annotationsEnable: '開放讀者針對段落註解',
        annotationsDisable: '關閉段落註解',
        annotationsOn: '開放',
        annotationsOff: '關閉',
        annotationsUpdatedOn: '已開放段落註解。',
        annotationsUpdatedOff: '已關閉段落註解。',
        shareExpiration: '有效期限',
        shareExpirationNever: '永久有效（預設）',
        shareExpiration10m: '10 分鐘',
        shareExpiration1h: '1 小時',
        shareExpiration1d: '1 天 (24小時)',
        shareExpiration7d: '7 天 (1週)',
        shareExpiration30d: '30 天 (1個月)',
        burnAfterReading: '閱後即焚',
        burnAfterReadingOn: '已開啟',
        burnAfterReadingOff: '未開啟',
        burnAfterReadingHint: '外部訪客讀取一次即自動銷毀（作者預覽不計）',
        burnRevealTitle: '機密分享 • 閱後即焚',
        burnRevealDesc: '這是作者設定的一次性機密分享，僅供閱讀一次。點擊下方按鈕將解鎖內容，並永久從伺服器銷毀此分享連結。',
        burnRevealBtn: '點擊閱讀並立即銷毀',
        burnRevealWarning: '注意：銷毀後若關閉視窗或重新整理，將無法再次檢視。',
        shareBurnedTitle: '分享已銷毀',
        shareBurnedDesc: '此分享為「閱後即焚」機密內容，已被他人讀取並永久銷毀。',
        shareExpiredTitle: '分享已過期',
        shareExpiredDesc: '此分享連結的有效期限已截止，無法再進行存取。',
        authorPreviewNotice: '作者預覽視角：閱後即焚與到期計時對您無效，外部訪客閱讀才會觸發銷毀。',
        burnActiveNotice: '此分享已自伺服器永久銷毀，關閉分頁或重新整理將無法再次閱讀。',
        shareVaultMode: 'Seal 存取控制',
        shareModeStandard: '標準發布',
        shareModeBurn: '閱後即焚',
        shareModeTimeLock: '定時解鎖 (時間膠囊)',
        shareModeDeadman: '亡者開關 (保活心跳)',
        shareUnlockIn: '解鎖時間',
        shareUnlockIn1h: '1 小時後',
        shareUnlockIn1d: '1 天後',
        shareUnlockIn3d: '3 天後',
        shareUnlockIn7d: '7 天後 (1週)',
        shareUnlockIn30d: '30 天後 (1個月)',
        shareTimeLockedTitle: '時間膠囊封印中',
        shareTimeLockedDesc: '此筆記已封印鎖定，將於預定解鎖時間到達後自動公開。',
        shareDeadmanTitle: '亡者開關保活中',
        shareDeadmanDesc: '作者心跳簽到正常，筆記處於 Seal 封印狀態。若作者失聯超期未簽到，將自動對外公開。',
        pulseInterval: '簽到保活週期',
        pulseInterval3d: '3 天',
        pulseInterval7d: '7 天 (1週)',
        pulseInterval14d: '14 天 (2週)',
        pulseInterval30d: '30 天 (1個月)',
        pulseNowBtn: '立即簽到保活 (Pulse)',
        pulseSuccess: '簽到保活成功！下次心跳截止時間已刷新。',
        pulseCopyLink: '複製作者專用保活連結',
        pulseCopied: '作者專用保活連結已複製！請妥善保存，切勿分享給他人。',
        authorTimeLockPreview: '作者預覽視角：此時間膠囊對外封印中，將於 {time} 自動解鎖。',
        authorDeadmanPreview: '作者預覽視角：亡者開關監控中，下次心跳截止：{time}。',
        shareLink: '分享頁',
        shareLinkTitle: '另開分頁開啟分享頁',
        recentSharesTitle: '最近分享',
        editLockTitle: '編輯鎖',
        readLockTitle: '閱讀鎖',
        backToEdit: '返回編輯',
        present: '演示',
        presentTitle: '進入全螢幕簡報模式',
        presentationUnavailable: '無內容可演示',
        presentationClose: '結束演示',
        presentationFailed: '啟動失敗: ',
        width: '寬度',
        full: '完整',
        previewDevice: '預覽裝置',
        desktop: '桌面',
        mobile: '手機',
        skill: 'Skill',
        skillTitle: '開啟 AI Skill Markdown',
        apiDoc: 'API',
        apiDocTitle: '開啟 API Markdown 文檔',
        startRecording: '即時錄音',
        importMarkdown: '匯入 Office、PDF、音訊逐字稿或 Markdown 檔案',
        importFileMarkdown: '匯入檔案（建立 Markdown 筆記）',
        importAudioMarkdown: '匯入音訊（逐字稿）',
        importAudioSmartFormatMarkdown: '匯入音訊（智慧排版）',
        importWebsiteMarkdown: '匯入網站（建立 Markdown 筆記）',
        importFileBlock: '匯入檔案（轉成 Block）',
        importAudioBlock: '匯入音訊（逐字稿轉 Block）',
        importAudioSmartFormatBlock: '匯入音訊（智慧排版轉 Block）',
        importWebsiteBlock: '匯入網站（轉成 Block）',
        creatingMarkdownNote: '正在建立 Markdown 筆記...',
        importBlockMessage: '匯入內容會轉換成 Block 區塊，部分特殊 Markdown 可能簡化。',
        importActionInsertBlock: '插入目前區塊後',
        exportMarkdown: '導出 Markdown 文件',
        exportPdf: '列印預覽或導出 PDF',
        convertingDocument: '正在將文件轉換為 Markdown...',
        transcribingAudio: '正在轉錄音訊為逐字稿...',
        transcribingAudioSmartFormat: '正在轉錄音訊並使用 AI 智慧整理排版...',
        markdownImported: '已導入 Markdown。',
        documentImported: '文件已成功轉換並導入。',
        audioTranscribed: '音訊已成功轉錄為逐字稿！',
        audioSmartFormatted: '音訊逐字稿已成功智慧整理排版！',
        markdownImportFailed: '文件轉換或導入失敗',
        audioTranscribeFailed: '音訊轉錄失敗',
        importOptionTitle: '匯入選項',
        importOptionMessage: '請選擇如何處理匯入的文件內容：',
        importActionReplace: '取代全文',
        importActionInsert: '插入游標處',
        importActionCancel: '取消',
        savedAtTitle: '保存時間',
        language: '語言',
        publishNudgeTitle: '要儲存並發布這篇文章嗎？',
        publishNudgeText: '未發布文章目前不會儲存。現在發布即可同步儲存目前內容並取得分享 URL。',
        publishApplyChoices: '套用選擇',
        publishPreferencePublish: '發布',
        publishPreferencePublishHelp: '儲存目前文章並建立公開分享 URL。',
        publishPreferenceAutosave: '自動儲存',
        publishPreferenceAutosaveHelp: '停止輸入 10 秒後自動儲存修改。',
        publishPreferencePublicIndex: '公開索引',
        publishPreferencePublicIndexHelp: '將分享 URL 加入 sitemap.xml，讓搜尋引擎有機會找到。',
        publishPreferencesRemembered: '這些選擇會記錄在這台裝置。',
        publicationDraft: '尚未發布',
        publicationPublished: '已發布',
        publicationUrl: '分享 URL',
        publicationVersions: '保留版本',
        publicationViews: '不重複瀏覽',
        publicationUpdated: '最後儲存',
        publicationPendingHint: '發布後會在這裡顯示分享 URL 與讀者統計。',
        later: '稍後',
        unpublishConfirm: '確定要取消發布此分享連結嗎？',
        uploadFailed: '上傳失敗',
        uploadError: '上傳錯誤: ',
        uploading: '上傳中...',
        err: '出錯了',
        pepw: '請輸入密碼',
        passwordConfirm: '確認',
        passwordCancel: '取消',
        pwcnbe: '密碼不能為空！',
        enpw: '輸入新密碼（留空可清除當前密碼）',
        pwss: '密碼設置成功！',
        pwrs: '密碼清除成功！',
        shareAndHistory: '分享與版本',
        history: '版本',
        historyTitle: '版本紀錄',
        historyPreview: '預覽',
        historyRaw: '原文',
        historyRefresh: '刷新',
        historyRestore: '還原',
        historyCopyContent: '複製內容',
        historyCurrentVersion: '目前版本',
        historySelectedVersion: '選取版本',
        historyNoSelection: '請先選一個版本來比較。',
        historyLoading: '正在讀取版本紀錄...',
        historyEmpty: '目前還沒有可用的歷史版本。之後保留下來的舊版本會顯示在這裡。',
        historyDisabled: '此部署尚未開啟歷史版本功能。',
        historyUnavailableOnShare: '歷史版本只會在編輯頁提供。',
        historyRestoreConfirm: '確定要還原這個版本並覆蓋目前內容嗎？',
        historyRestoreDone: '已還原此版本。',
        historyCopiedContent: '已複製內容。',
        historyChars: '字',
    }
}
