// static CDN
// static CDN
export const CDN_PREFIX = 'https://cdn.jsdelivr.net/npm'

const readRuntimeVar = name => globalThis?.[name]

// server side salt
export const SALT = readRuntimeVar('SCN_SALT')
// server side secret
export const SECRET = readRuntimeVar('SCN_SECRET')

// admin
export const ADMIN_PATH = readRuntimeVar('SCN_ADMIN_PATH') || '/admin'
export const ADMIN_PW = readRuntimeVar('SCN_ADMIN_PW')
export const SLUG_LENGTH = parseInt(readRuntimeVar('SCN_SLUG_LENGTH') || '3')
// Access R2 config at runtime instead of module load time
export const getEnableR2 = () => readRuntimeVar('SCN_ENABLE_R2') === '1'
export const getR2Domain = () => (typeof readRuntimeVar('SCN_R2_DOMAIN') !== 'undefined' ? readRuntimeVar('SCN_R2_DOMAIN') : '')
export const getGaMeasurementId = () => (typeof readRuntimeVar('SCN_GA_MEASUREMENT_ID') !== 'undefined' ? String(readRuntimeVar('SCN_GA_MEASUREMENT_ID') || '').trim() : '')
export const APP_NAME = (typeof readRuntimeVar('SCN_APP_NAME') !== 'undefined') ? readRuntimeVar('SCN_APP_NAME') : 'david888 wiki'

// supported language
export const SUPPORTED_LANG = {
    'en-US': {
        setPW: 'Edit Lock',
        changePW: 'Edit Lock',
        setViewPW: 'Read Lock',
        changeViewPW: 'Read Lock',
        share: 'Share URL',
        preview: 'Preview',
        lastModified: 'Saved',
        copy: 'Copy',
        copied: 'Copied!',
        copyFailed: 'Copy failed',
        emptyPH: 'There are many like it, but this one is mine...',
        tipEncrypt: 'This Note has been encrypted, please enter password!',
        tip404: '404, Nothing here',
        published: 'Published:',
        backToEdit: 'Back to edit',
        present: 'Present',
        presentTitle: 'Open full-screen presentation mode',
        presentationUnavailable: 'No content to present',
        presentationClose: 'Close presentation',
        presentationFailed: 'Presentation failed: ',
        width: 'Width',
        full: 'Full',
        previewDevice: 'Preview device',
        desktop: 'Desktop',
        mobile: 'Mobile',
        skill: 'Skill',
        language: 'Language',
        publishNudgeTitle: 'Ready to publish?',
        publishNudgeText: 'You have been editing for a while. Publish this note to get a share URL.',
        publishNow: 'Publish',
        later: 'Later',
        unpublishConfirm: 'Unpublish this share link?',
        uploadFailed: 'Upload failed',
        uploadError: 'Upload error: ',
        uploading: 'Uploading...',
        err: 'Error',
        pepw: 'Please enter password.',
        pwcnbe: 'Password is empty!',
        enpw: 'Enter a new password (Keeping it empty will remove the current password)',
        pwss: 'Password set successfully.',
        pwrs: 'Password removed successfully.',
        shareAndHistory: 'Shares & history',
        history: 'History',
        historyPreview: 'Preview',
        historyRaw: 'Raw',
        historyRefresh: 'Refresh',
        historyRestore: 'Restore',
        historyCopyContent: 'Copy content',
        historyCurrentVersion: 'Current',
        historySelectedVersion: 'Selected',
        historyNoSelection: 'Select a version to compare.',
        historyLoading: 'Loading history...',
        historyEmpty: 'No saved history yet. Once older versions are retained, they will appear here.',
        historyDisabled: 'Note history is disabled for this deployment.',
        historyUnavailableOnShare: 'Version history is only available on the edit page.',
        historyRestoreConfirm: 'Restore this version and overwrite the current note?',
        historyRestoreDone: 'Version restored.',
        historyCopiedContent: 'Content copied.',
        historyChars: 'chars',
    },
    'zh-TW': {
        setPW: '編輯鎖',
        changePW: '編輯鎖',
        setViewPW: '閱讀鎖',
        changeViewPW: '閱讀鎖',
        share: '發布分享',
        preview: '預覽',
        lastModified: '保存',
        copy: '複製',
        copied: '已複製',
        copyFailed: '複製失敗',
        emptyPH: '看來你是第一個到這裡的人，寫點什麼吧...寫完後，記得按下發布分享按鈕取得URL',
        tipEncrypt: '這是一篇加密筆記，你必須先輸入密碼',
        tip404: '404，你要找的東西並不存在',
        published: '已發布:',
        backToEdit: '返回編輯',
        present: '演示',
        presentTitle: '進入全螢幕簡報模式',
        presentationUnavailable: '無內容可演示',
        presentationClose: '結束演示',
        presentationFailed: '啟動失敗: ',
        width: '寬度',
        full: '完整',
        previewDevice: '預覽裝置',
        desktop: '桌面',
        mobile: '手機',
        skill: 'Skill',
        language: '語言',
        publishNudgeTitle: '要發布分享嗎？',
        publishNudgeText: '你已在輸入區停留一段時間。發布後即可取得分享 URL。',
        publishNow: '發布',
        later: '稍後',
        unpublishConfirm: '確定要取消發布此分享連結嗎？',
        uploadFailed: '上傳失敗',
        uploadError: '上傳錯誤: ',
        uploading: '上傳中...',
        err: '出錯了',
        pepw: '請輸入密碼',
        pwcnbe: '密碼不能為空！',
        enpw: '輸入新密碼（留空可清除當前密碼）',
        pwss: '密碼設置成功！',
        pwrs: '密碼清除成功！',
        shareAndHistory: '分享與版本',
        history: '版本',
        historyPreview: '預覽',
        historyRaw: '原文',
        historyRefresh: '刷新',
        historyRestore: '還原',
        historyCopyContent: '複製內容',
        historyCurrentVersion: '目前版本',
        historySelectedVersion: '選取版本',
        historyNoSelection: '請先選一個版本來比較。',
        historyLoading: '正在讀取版本紀錄...',
        historyEmpty: '目前還沒有可用的歷史版本。之後保留下來的舊版本會顯示在這裡。',
        historyDisabled: '此部署尚未開啟歷史版本功能。',
        historyUnavailableOnShare: '歷史版本只會在編輯頁提供。',
        historyRestoreConfirm: '確定要還原這個版本並覆蓋目前內容嗎？',
        historyRestoreDone: '已還原此版本。',
        historyCopiedContent: '已複製內容。',
        historyChars: '字',
    }
}
