// static CDN
// static CDN
export const CDN_PREFIX = 'https://cdn.jsdelivr.net/npm'

const readRuntimeVar = name => globalThis?.[name]

// server side salt
export const SALT = readRuntimeVar('SCN_SALT')
// server side secret
export const SECRET = readRuntimeVar('SCN_SECRET')
export const getSalt = () => readRuntimeVar('SCN_SALT')
export const getSecret = () => readRuntimeVar('SCN_SECRET')

// admin
export const getAdminPath = () => readRuntimeVar('SCN_ADMIN_PATH') || '/admin'
export const getAdminPassword = () => readRuntimeVar('SCN_ADMIN_PW')
// Kept for compatibility with callers that import the old constants. Request
// handlers should use the getters because Cloudflare bindings are available
// after the Worker module has been evaluated.
export const ADMIN_PATH = getAdminPath()
export const ADMIN_PW = getAdminPassword()
export const SLUG_LENGTH = parseInt(readRuntimeVar('SCN_SLUG_LENGTH') || '3')
// Access R2 config at runtime instead of module load time
export const getEnableR2 = () => readRuntimeVar('SCN_ENABLE_R2') === '1'
export const getR2Domain = () => (typeof readRuntimeVar('SCN_R2_DOMAIN') !== 'undefined' ? readRuntimeVar('SCN_R2_DOMAIN') : '')
export const getGaMeasurementId = () => (typeof readRuntimeVar('SCN_GA_MEASUREMENT_ID') !== 'undefined' ? String(readRuntimeVar('SCN_GA_MEASUREMENT_ID') || '').trim() : '')
export const APP_NAME = (typeof readRuntimeVar('SCN_APP_NAME') !== 'undefined') ? readRuntimeVar('SCN_APP_NAME') : 'david888 wiki'

// supported language
export const SUPPORTED_LANG = {
    'en-US': {
        setPW: 'Edit Lock',
        changePW: 'Edit Lock',
        setViewPW: 'View Lock',
        changeViewPW: 'View Lock',
        share: 'Share URL',
        preview: 'Preview',
        lastModified: 'Saved',
        copy: 'Copy',
        copied: 'Copied!',
        copyFailed: 'Copy failed',
        emptyPH: 'There are many like it, but this one is mine...',
        tipEncrypt: 'This Note has been encrypted, please enter password!',
        tip404: '404, Nothing here',
        published: 'Published',
        publicIndex: 'Public index',
        publicIndexEnable: 'Add to sitemap',
        publicIndexDisable: 'Remove from sitemap',
        publicIndexOn: 'Indexed',
        publicIndexOff: 'Private',
        publicIndexPromptTitle: 'Add this share link to the public index?',
        publicIndexPromptText: 'Only links you explicitly approve will be included in sitemap.xml. You can change this later.',
        publicIndexPromptApprove: 'Yes, add it',
        publicIndexPromptDecline: 'No, keep it private',
        publicIndexUpdatedOn: 'Added to public index.',
        publicIndexUpdatedOff: 'Removed from public index.',
        shareLink: 'Share',
        shareLinkTitle: 'Open shared page in a new tab',
        recentSharesTitle: 'Recent shares',
        editLockTitle: 'Edit lock',
        readLockTitle: 'View lock',
        backToEdit: 'Back to edit',
        present: 'Present',
        presentTitle: 'Open full-screen presentation mode',
        presentationUnavailable: 'No content to present',
        presentationClose: 'Close presentation',
        presentationFailed: 'Presentation failed: ',
        width: 'Width',
        full: 'Full',
        previewDevice: 'Preview device',
        desktop: 'Desktop',
        mobile: 'Mobile',
        skill: 'Skill',
        skillTitle: 'Open AI skill markdown',
        apiDoc: 'API',
        apiDocTitle: 'Open API markdown documentation',
        importMarkdown: 'Import markdown file',
        exportMarkdown: 'Export markdown file',
        exportPdf: 'Print or export PDF',
        markdownImported: 'Markdown imported.',
        markdownImportFailed: 'Markdown import failed',
        savedAtTitle: 'Saved at',
        language: 'Language',
        publishNudgeTitle: 'Save and publish this note?',
        publishNudgeText: 'This unpublished note is not saved yet. Publish now to save the current content and get a share URL.',
        publishAndSave: 'Publish and save',
        autosaveNudgeTitle: 'Enable autosave?',
        autosaveNudgeText: 'This note is published. Would you like to automatically save changes 10 seconds after you stop typing?',
        autosaveEnable: 'Enable autosave',
        autosaveEnabled: 'Autosave enabled',
        later: 'Later',
        unpublishConfirm: 'Unpublish this share link?',
        uploadFailed: 'Upload failed',
        uploadError: 'Upload error: ',
        uploading: 'Uploading...',
        err: 'Error',
        pepw: 'Please enter password.',
        passwordConfirm: 'Continue',
        passwordCancel: 'Cancel',
        pwcnbe: 'Password is empty!',
        enpw: 'Enter a new password (Keeping it empty will remove the current password)',
        pwss: 'Password set successfully.',
        pwrs: 'Password removed successfully.',
        shareAndHistory: 'Shares & history',
        history: 'History',
        historyTitle: 'Version history',
        historyPreview: 'Preview',
        historyRaw: 'Raw',
        historyRefresh: 'Refresh',
        historyRestore: 'Restore',
        historyCopyContent: 'Copy content',
        historyCurrentVersion: 'Current',
        historySelectedVersion: 'Selected',
        historyNoSelection: 'Select a version to compare.',
        historyLoading: 'Loading history...',
        historyEmpty: 'No saved history yet. Once older versions are retained, they will appear here.',
        historyDisabled: 'Note history is disabled for this deployment.',
        historyUnavailableOnShare: 'Version history is only available on the edit page.',
        historyRestoreConfirm: 'Restore this version and overwrite the current note?',
        historyRestoreDone: 'Version restored.',
        historyCopiedContent: 'Content copied.',
        historyChars: 'chars',
    },
    'zh-TW': {
        setPW: '編輯鎖',
        changePW: '編輯鎖',
        setViewPW: '閱讀鎖',
        changeViewPW: '閱讀鎖',
        share: '發布分享',
        preview: '預覽',
        lastModified: '保存',
        copy: '複製',
        copied: '已複製',
        copyFailed: '複製失敗',
        emptyPH: '看來你是第一個到這裡的人，寫點什麼吧...寫完後，記得按下發布分享按鈕取得URL',
        tipEncrypt: '這是一篇加密筆記，你必須先輸入密碼',
        tip404: '404，你要找的東西並不存在',
        published: '已發布',
        publicIndex: '公開索引',
        publicIndexEnable: '加入 sitemap',
        publicIndexDisable: '移出 sitemap',
        publicIndexOn: '已收錄',
        publicIndexOff: '未收錄',
        publicIndexPromptTitle: '要把這個分享連結加入公開索引嗎？',
        publicIndexPromptText: '只有你明確同意的分享連結才會進入 sitemap.xml。之後也可以再修改。',
        publicIndexPromptApprove: '同意加入',
        publicIndexPromptDecline: '不同意',
        publicIndexUpdatedOn: '已加入公開索引。',
        publicIndexUpdatedOff: '已從公開索引移除。',
        shareLink: '分享頁',
        shareLinkTitle: '另開分頁開啟分享頁',
        recentSharesTitle: '最近分享',
        editLockTitle: '編輯鎖',
        readLockTitle: '閱讀鎖',
        backToEdit: '返回編輯',
        present: '演示',
        presentTitle: '進入全螢幕簡報模式',
        presentationUnavailable: '無內容可演示',
        presentationClose: '結束演示',
        presentationFailed: '啟動失敗: ',
        width: '寬度',
        full: '完整',
        previewDevice: '預覽裝置',
        desktop: '桌面',
        mobile: '手機',
        skill: 'Skill',
        skillTitle: '開啟 AI Skill Markdown',
        apiDoc: 'API',
        apiDocTitle: '開啟 API Markdown 文檔',
        importMarkdown: '導入 Markdown 文件',
        exportMarkdown: '導出 Markdown 文件',
        exportPdf: '列印預覽或導出 PDF',
        markdownImported: '已導入 Markdown。',
        markdownImportFailed: 'Markdown 導入失敗',
        savedAtTitle: '保存時間',
        language: '語言',
        publishNudgeTitle: '要儲存並發布這篇文章嗎？',
        publishNudgeText: '未發布文章目前不會儲存。現在發布即可同步儲存目前內容並取得分享 URL。',
        publishAndSave: '發布並儲存',
        autosaveNudgeTitle: '要開啟自動儲存嗎？',
        autosaveNudgeText: '文章已發布。要不要在停止輸入 10 秒後自動儲存修改？',
        autosaveEnable: '開啟自動儲存',
        autosaveEnabled: '已開啟自動儲存',
        later: '稍後',
        unpublishConfirm: '確定要取消發布此分享連結嗎？',
        uploadFailed: '上傳失敗',
        uploadError: '上傳錯誤: ',
        uploading: '上傳中...',
        err: '出錯了',
        pepw: '請輸入密碼',
        passwordConfirm: '確認',
        passwordCancel: '取消',
        pwcnbe: '密碼不能為空！',
        enpw: '輸入新密碼（留空可清除當前密碼）',
        pwss: '密碼設置成功！',
        pwrs: '密碼清除成功！',
        shareAndHistory: '分享與版本',
        history: '版本',
        historyTitle: '版本紀錄',
        historyPreview: '預覽',
        historyRaw: '原文',
        historyRefresh: '刷新',
        historyRestore: '還原',
        historyCopyContent: '複製內容',
        historyCurrentVersion: '目前版本',
        historySelectedVersion: '選取版本',
        historyNoSelection: '請先選一個版本來比較。',
        historyLoading: '正在讀取版本紀錄...',
        historyEmpty: '目前還沒有可用的歷史版本。之後保留下來的舊版本會顯示在這裡。',
        historyDisabled: '此部署尚未開啟歷史版本功能。',
        historyUnavailableOnShare: '歷史版本只會在編輯頁提供。',
        historyRestoreConfirm: '確定要還原這個版本並覆蓋目前內容嗎？',
        historyRestoreDone: '已還原此版本。',
        historyCopiedContent: '已複製內容。',
        historyChars: '字',
    }
}
